window.env = {
    FIREBASE_API_KEY: "",
    FIREBASE_AUTH_DOMAIN: "",
    FIREBASE_DATABASE_URL: "",
    FIREBASE_PROJECT_ID: "",
    FIREBASE_STORAGE_BUCKET: "",
    FIREBASE_MESSAGING_SENDER_ID: "",
    FIREBASE_APP_ID: "",
    FORMSPREE_URL: "",
    AI_DEV_PROXY: "http://127.0.0.1:3117/api/ai",
    GEMINI_API_KEY: ""
};
